/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq;


import app.preach.gospel.jooq.tables.Authorities;
import app.preach.gospel.jooq.tables.Hymns;
import app.preach.gospel.jooq.tables.HymnsWork;
import app.preach.gospel.jooq.tables.Roles;
import app.preach.gospel.jooq.tables.Students;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTH_NAME = Internal.createIndex(DSL.name("auth_name"), Authorities.AUTHORITIES, new OrderField[] { Authorities.AUTHORITIES.NAME }, true);
    public static final Index AUTH_TITLE = Internal.createIndex(DSL.name("auth_title"), Authorities.AUTHORITIES, new OrderField[] { Authorities.AUTHORITIES.TITLE }, true);
    public static final Index HYMN_LINK = Internal.createIndex(DSL.name("hymn_link"), Hymns.HYMNS, new OrderField[] { Hymns.HYMNS.LINK }, true);
    public static final Index HYMN_NAME_JP = Internal.createIndex(DSL.name("hymn_name_jp"), Hymns.HYMNS, new OrderField[] { Hymns.HYMNS.NAME_JP }, true);
    public static final Index HYMN_NAME_KR = Internal.createIndex(DSL.name("hymn_name_kr"), Hymns.HYMNS, new OrderField[] { Hymns.HYMNS.NAME_KR }, true);
    public static final Index HYMNS_WORK_WORK_ID_KEY = Internal.createIndex(DSL.name("hymns_work_work_id_key"), HymnsWork.HYMNS_WORK, new OrderField[] { HymnsWork.HYMNS_WORK.WORK_ID }, true);
    public static final Index IDX_HYMNS_NJP_TRGM = Internal.createIndex(DSL.name("idx_hymns_njp_trgm"), Hymns.HYMNS, new OrderField[] { Hymns.HYMNS.NAME_JP }, false);
    public static final Index IDX_HYMNS_NKR_TRGM = Internal.createIndex(DSL.name("idx_hymns_nkr_trgm"), Hymns.HYMNS, new OrderField[] { Hymns.HYMNS.NAME_KR }, false);
    public static final Index ROLE_NAME = Internal.createIndex(DSL.name("role_name"), Roles.ROLES, new OrderField[] { Roles.ROLES.NAME }, true);
    public static final Index ROLES_NAME_UK = Internal.createIndex(DSL.name("roles_name_uk"), Roles.ROLES, new OrderField[] { Roles.ROLES.NAME }, true);
    public static final Index STUDENT_EMAIL = Internal.createIndex(DSL.name("student_email"), Students.STUDENTS, new OrderField[] { Students.STUDENTS.EMAIL }, true);
    public static final Index STUDENT_LOGIN_ACCOUNT = Internal.createIndex(DSL.name("student_login_account"), Students.STUDENTS, new OrderField[] { Students.STUDENTS.LOGIN_ACCOUNT }, true);
}
