/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq;


import app.preach.gospel.jooq.tables.Authorities;
import app.preach.gospel.jooq.tables.Books;
import app.preach.gospel.jooq.tables.Chapters;
import app.preach.gospel.jooq.tables.Hymns;
import app.preach.gospel.jooq.tables.HymnsWork;
import app.preach.gospel.jooq.tables.Phrases;
import app.preach.gospel.jooq.tables.Receipts;
import app.preach.gospel.jooq.tables.RoleAuth;
import app.preach.gospel.jooq.tables.Roles;
import app.preach.gospel.jooq.tables.Students;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.authorities</code>.
     */
    public final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>public.books</code>.
     */
    public final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.chapters</code>.
     */
    public final Chapters CHAPTERS = Chapters.CHAPTERS;

    /**
     * The table <code>public.hymns</code>.
     */
    public final Hymns HYMNS = Hymns.HYMNS;

    /**
     * The table <code>public.hymns_work</code>.
     */
    public final HymnsWork HYMNS_WORK = HymnsWork.HYMNS_WORK;

    /**
     * The table <code>public.phrases</code>.
     */
    public final Phrases PHRASES = Phrases.PHRASES;

    /**
     * レシート
     */
    public final Receipts RECEIPTS = Receipts.RECEIPTS;

    /**
     * The table <code>public.role_auth</code>.
     */
    public final RoleAuth ROLE_AUTH = RoleAuth.ROLE_AUTH;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Authorities.AUTHORITIES,
            Books.BOOKS,
            Chapters.CHAPTERS,
            Hymns.HYMNS,
            HymnsWork.HYMNS_WORK,
            Phrases.PHRASES,
            Receipts.RECEIPTS,
            RoleAuth.ROLE_AUTH,
            Roles.ROLES,
            Students.STUDENTS
        );
    }
}
