/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq;


import app.preach.gospel.jooq.tables.Authorities;
import app.preach.gospel.jooq.tables.Books;
import app.preach.gospel.jooq.tables.Chapters;
import app.preach.gospel.jooq.tables.Hymns;
import app.preach.gospel.jooq.tables.HymnsWork;
import app.preach.gospel.jooq.tables.Phrases;
import app.preach.gospel.jooq.tables.Receipts;
import app.preach.gospel.jooq.tables.RoleAuth;
import app.preach.gospel.jooq.tables.Roles;
import app.preach.gospel.jooq.tables.Students;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.authorities</code>.
     */
    public static final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.chapters</code>.
     */
    public static final Chapters CHAPTERS = Chapters.CHAPTERS;

    /**
     * The table <code>public.hymns</code>.
     */
    public static final Hymns HYMNS = Hymns.HYMNS;

    /**
     * The table <code>public.hymns_work</code>.
     */
    public static final HymnsWork HYMNS_WORK = HymnsWork.HYMNS_WORK;

    /**
     * The table <code>public.phrases</code>.
     */
    public static final Phrases PHRASES = Phrases.PHRASES;

    /**
     * レシート
     */
    public static final Receipts RECEIPTS = Receipts.RECEIPTS;

    /**
     * The table <code>public.role_auth</code>.
     */
    public static final RoleAuth ROLE_AUTH = RoleAuth.ROLE_AUTH;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;
}
