/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables;


import app.preach.gospel.jooq.Indexes;
import app.preach.gospel.jooq.Keys;
import app.preach.gospel.jooq.Public;
import app.preach.gospel.jooq.tables.Hymns.HymnsPath;
import app.preach.gospel.jooq.tables.records.HymnsWorkRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HymnsWork extends TableImpl<HymnsWorkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.hymns_work</code>
     */
    public static final HymnsWork HYMNS_WORK = new HymnsWork();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HymnsWorkRecord> getRecordType() {
        return HymnsWorkRecord.class;
    }

    /**
     * The column <code>public.hymns_work.id</code>. ID
     */
    public final TableField<HymnsWorkRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "ID");

    /**
     * The column <code>public.hymns_work.work_id</code>. ワークID
     */
    public final TableField<HymnsWorkRecord, Long> WORK_ID = createField(DSL.name("work_id"), SQLDataType.BIGINT.nullable(false), this, "ワークID");

    /**
     * The column <code>public.hymns_work.score</code>. 楽譜
     */
    public final TableField<HymnsWorkRecord, byte[]> SCORE = createField(DSL.name("score"), SQLDataType.BLOB, this, "楽譜");

    /**
     * The column <code>public.hymns_work.furigana</code>. 振り仮名
     */
    public final TableField<HymnsWorkRecord, String> FURIGANA = createField(DSL.name("furigana"), SQLDataType.CLOB, this, "振り仮名");

    /**
     * The column <code>public.hymns_work.updated_time</code>. 更新時間
     */
    public final TableField<HymnsWorkRecord, OffsetDateTime> UPDATED_TIME = createField(DSL.name("updated_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "更新時間");

    /**
     * The column <code>public.hymns_work.biko</code>. 備考
     */
    public final TableField<HymnsWorkRecord, String> BIKO = createField(DSL.name("biko"), SQLDataType.VARCHAR(15), this, "備考");

    private HymnsWork(Name alias, Table<HymnsWorkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HymnsWork(Name alias, Table<HymnsWorkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.hymns_work</code> table reference
     */
    public HymnsWork(String alias) {
        this(DSL.name(alias), HYMNS_WORK);
    }

    /**
     * Create an aliased <code>public.hymns_work</code> table reference
     */
    public HymnsWork(Name alias) {
        this(alias, HYMNS_WORK);
    }

    /**
     * Create a <code>public.hymns_work</code> table reference
     */
    public HymnsWork() {
        this(DSL.name("hymns_work"), null);
    }

    public <O extends Record> HymnsWork(Table<O> path, ForeignKey<O, HymnsWorkRecord> childPath, InverseForeignKey<O, HymnsWorkRecord> parentPath) {
        super(path, childPath, parentPath, HYMNS_WORK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HymnsWorkPath extends HymnsWork implements Path<HymnsWorkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HymnsWorkPath(Table<O> path, ForeignKey<O, HymnsWorkRecord> childPath, InverseForeignKey<O, HymnsWorkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HymnsWorkPath(Name alias, Table<HymnsWorkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HymnsWorkPath as(String alias) {
            return new HymnsWorkPath(DSL.name(alias), this);
        }

        @Override
        public HymnsWorkPath as(Name alias) {
            return new HymnsWorkPath(alias, this);
        }

        @Override
        public HymnsWorkPath as(Table<?> alias) {
            return new HymnsWorkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HYMNS_WORK_WORK_ID_KEY);
    }

    @Override
    public UniqueKey<HymnsWorkRecord> getPrimaryKey() {
        return Keys.HYMNS_WORK_PKEY;
    }

    @Override
    public List<ForeignKey<HymnsWorkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HYMNS_WORK__HYMNS_WORK_HYMNS_TO_WORK);
    }

    private transient HymnsPath _hymns;

    /**
     * Get the implicit join path to the <code>public.hymns</code> table.
     */
    public HymnsPath hymns() {
        if (_hymns == null)
            _hymns = new HymnsPath(this, Keys.HYMNS_WORK__HYMNS_WORK_HYMNS_TO_WORK, null);

        return _hymns;
    }

    @Override
    public HymnsWork as(String alias) {
        return new HymnsWork(DSL.name(alias), this);
    }

    @Override
    public HymnsWork as(Name alias) {
        return new HymnsWork(alias, this);
    }

    @Override
    public HymnsWork as(Table<?> alias) {
        return new HymnsWork(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HymnsWork rename(String name) {
        return new HymnsWork(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HymnsWork rename(Name name) {
        return new HymnsWork(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HymnsWork rename(Table<?> name) {
        return new HymnsWork(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HymnsWork where(Condition condition) {
        return new HymnsWork(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HymnsWork where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HymnsWork where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HymnsWork where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HymnsWork where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HymnsWork where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HymnsWork where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HymnsWork where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HymnsWork whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HymnsWork whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
