/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables;


import app.preach.gospel.jooq.Indexes;
import app.preach.gospel.jooq.Keys;
import app.preach.gospel.jooq.Public;
import app.preach.gospel.jooq.tables.HymnsWork.HymnsWorkPath;
import app.preach.gospel.jooq.tables.Students.StudentsPath;
import app.preach.gospel.jooq.tables.records.HymnsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Hymns extends TableImpl<HymnsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.hymns</code>
     */
    public static final Hymns HYMNS = new Hymns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HymnsRecord> getRecordType() {
        return HymnsRecord.class;
    }

    /**
     * The column <code>public.hymns.id</code>. ID
     */
    public final TableField<HymnsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("'0'::bigint"), SQLDataType.BIGINT)), this, "ID");

    /**
     * The column <code>public.hymns.name_jp</code>. 日本語名称
     */
    public final TableField<HymnsRecord, String> NAME_JP = createField(DSL.name("name_jp"), SQLDataType.VARCHAR(66).nullable(false), this, "日本語名称");

    /**
     * The column <code>public.hymns.name_kr</code>. 韓国語名称
     */
    public final TableField<HymnsRecord, String> NAME_KR = createField(DSL.name("name_kr"), SQLDataType.VARCHAR(66).nullable(false), this, "韓国語名称");

    /**
     * The column <code>public.hymns.link</code>. リンク
     */
    public final TableField<HymnsRecord, String> LINK = createField(DSL.name("link"), SQLDataType.VARCHAR(255), this, "リンク");

    /**
     * The column <code>public.hymns.updated_time</code>. 更新時間
     */
    public final TableField<HymnsRecord, OffsetDateTime> UPDATED_TIME = createField(DSL.name("updated_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "更新時間");

    /**
     * The column <code>public.hymns.updated_user</code>. 更新者ID
     */
    public final TableField<HymnsRecord, Long> UPDATED_USER = createField(DSL.name("updated_user"), SQLDataType.BIGINT.nullable(false), this, "更新者ID");

    /**
     * The column <code>public.hymns.lyric</code>. 歌詞
     */
    public final TableField<HymnsRecord, String> LYRIC = createField(DSL.name("lyric"), SQLDataType.CLOB, this, "歌詞");

    /**
     * The column <code>public.hymns.visible_flg</code>. 論理削除フラグ
     */
    public final TableField<HymnsRecord, Boolean> VISIBLE_FLG = createField(DSL.name("visible_flg"), SQLDataType.BOOLEAN.nullable(false), this, "論理削除フラグ");

    /**
     * The column <code>public.hymns.classical</code>.
     */
    public final TableField<HymnsRecord, Boolean> CLASSICAL = createField(DSL.name("classical"), SQLDataType.BOOLEAN, this, "");

    private Hymns(Name alias, Table<HymnsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Hymns(Name alias, Table<HymnsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.hymns</code> table reference
     */
    public Hymns(String alias) {
        this(DSL.name(alias), HYMNS);
    }

    /**
     * Create an aliased <code>public.hymns</code> table reference
     */
    public Hymns(Name alias) {
        this(alias, HYMNS);
    }

    /**
     * Create a <code>public.hymns</code> table reference
     */
    public Hymns() {
        this(DSL.name("hymns"), null);
    }

    public <O extends Record> Hymns(Table<O> path, ForeignKey<O, HymnsRecord> childPath, InverseForeignKey<O, HymnsRecord> parentPath) {
        super(path, childPath, parentPath, HYMNS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HymnsPath extends Hymns implements Path<HymnsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HymnsPath(Table<O> path, ForeignKey<O, HymnsRecord> childPath, InverseForeignKey<O, HymnsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HymnsPath(Name alias, Table<HymnsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HymnsPath as(String alias) {
            return new HymnsPath(DSL.name(alias), this);
        }

        @Override
        public HymnsPath as(Name alias) {
            return new HymnsPath(alias, this);
        }

        @Override
        public HymnsPath as(Table<?> alias) {
            return new HymnsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HYMN_LINK, Indexes.HYMN_NAME_JP, Indexes.HYMN_NAME_KR, Indexes.IDX_HYMNS_NJP_TRGM, Indexes.IDX_HYMNS_NKR_TRGM);
    }

    @Override
    public UniqueKey<HymnsRecord> getPrimaryKey() {
        return Keys.HYMNS_PKEY;
    }

    @Override
    public List<ForeignKey<HymnsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HYMNS__HYMNS_STUDENTS_UPDATED_HYMNS);
    }

    private transient StudentsPath _students;

    /**
     * Get the implicit join path to the <code>public.students</code> table.
     */
    public StudentsPath students() {
        if (_students == null)
            _students = new StudentsPath(this, Keys.HYMNS__HYMNS_STUDENTS_UPDATED_HYMNS, null);

        return _students;
    }

    private transient HymnsWorkPath _hymnsWork;

    /**
     * Get the implicit to-many join path to the <code>public.hymns_work</code>
     * table
     */
    public HymnsWorkPath hymnsWork() {
        if (_hymnsWork == null)
            _hymnsWork = new HymnsWorkPath(this, null, Keys.HYMNS_WORK__HYMNS_WORK_HYMNS_TO_WORK.getInverseKey());

        return _hymnsWork;
    }

    @Override
    public Hymns as(String alias) {
        return new Hymns(DSL.name(alias), this);
    }

    @Override
    public Hymns as(Name alias) {
        return new Hymns(alias, this);
    }

    @Override
    public Hymns as(Table<?> alias) {
        return new Hymns(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hymns rename(String name) {
        return new Hymns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hymns rename(Name name) {
        return new Hymns(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hymns rename(Table<?> name) {
        return new Hymns(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hymns where(Condition condition) {
        return new Hymns(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hymns where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hymns where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hymns where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hymns where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hymns where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hymns where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hymns where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hymns whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hymns whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
