/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables;


import app.preach.gospel.jooq.Keys;
import app.preach.gospel.jooq.Public;
import app.preach.gospel.jooq.tables.Chapters.ChaptersPath;
import app.preach.gospel.jooq.tables.records.PhrasesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Phrases extends TableImpl<PhrasesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.phrases</code>
     */
    public static final Phrases PHRASES = new Phrases();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhrasesRecord> getRecordType() {
        return PhrasesRecord.class;
    }

    /**
     * The column <code>public.phrases.id</code>. 節ID
     */
    public final TableField<PhrasesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("'0'::bigint"), SQLDataType.BIGINT)), this, "節ID");

    /**
     * The column <code>public.phrases.name</code>. 節名称
     */
    public final TableField<PhrasesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(33).nullable(false), this, "節名称");

    /**
     * The column <code>public.phrases.text_en</code>. 内容
     */
    public final TableField<PhrasesRecord, String> TEXT_EN = createField(DSL.name("text_en"), SQLDataType.CLOB.nullable(false), this, "内容");

    /**
     * The column <code>public.phrases.text_jp</code>. 日本語内容
     */
    public final TableField<PhrasesRecord, String> TEXT_JP = createField(DSL.name("text_jp"), SQLDataType.CLOB.nullable(false), this, "日本語内容");

    /**
     * The column <code>public.phrases.chapter_id</code>. 章節ID
     */
    public final TableField<PhrasesRecord, Integer> CHAPTER_ID = createField(DSL.name("chapter_id"), SQLDataType.INTEGER.nullable(false), this, "章節ID");

    /**
     * The column <code>public.phrases.change_line</code>. 改行フラグ
     */
    public final TableField<PhrasesRecord, Boolean> CHANGE_LINE = createField(DSL.name("change_line"), SQLDataType.BOOLEAN.nullable(false), this, "改行フラグ");

    private Phrases(Name alias, Table<PhrasesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Phrases(Name alias, Table<PhrasesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.phrases</code> table reference
     */
    public Phrases(String alias) {
        this(DSL.name(alias), PHRASES);
    }

    /**
     * Create an aliased <code>public.phrases</code> table reference
     */
    public Phrases(Name alias) {
        this(alias, PHRASES);
    }

    /**
     * Create a <code>public.phrases</code> table reference
     */
    public Phrases() {
        this(DSL.name("phrases"), null);
    }

    public <O extends Record> Phrases(Table<O> path, ForeignKey<O, PhrasesRecord> childPath, InverseForeignKey<O, PhrasesRecord> parentPath) {
        super(path, childPath, parentPath, PHRASES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PhrasesPath extends Phrases implements Path<PhrasesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PhrasesPath(Table<O> path, ForeignKey<O, PhrasesRecord> childPath, InverseForeignKey<O, PhrasesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PhrasesPath(Name alias, Table<PhrasesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PhrasesPath as(String alias) {
            return new PhrasesPath(DSL.name(alias), this);
        }

        @Override
        public PhrasesPath as(Name alias) {
            return new PhrasesPath(alias, this);
        }

        @Override
        public PhrasesPath as(Table<?> alias) {
            return new PhrasesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PhrasesRecord> getPrimaryKey() {
        return Keys.PHRASES_PKEY;
    }

    @Override
    public List<ForeignKey<PhrasesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PHRASES__PHRASES_CHAPTERS_TO_PHRASE);
    }

    private transient ChaptersPath _chapters;

    /**
     * Get the implicit join path to the <code>public.chapters</code> table.
     */
    public ChaptersPath chapters() {
        if (_chapters == null)
            _chapters = new ChaptersPath(this, Keys.PHRASES__PHRASES_CHAPTERS_TO_PHRASE, null);

        return _chapters;
    }

    @Override
    public Phrases as(String alias) {
        return new Phrases(DSL.name(alias), this);
    }

    @Override
    public Phrases as(Name alias) {
        return new Phrases(alias, this);
    }

    @Override
    public Phrases as(Table<?> alias) {
        return new Phrases(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Phrases rename(String name) {
        return new Phrases(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Phrases rename(Name name) {
        return new Phrases(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Phrases rename(Table<?> name) {
        return new Phrases(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Phrases where(Condition condition) {
        return new Phrases(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Phrases where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Phrases where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Phrases where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Phrases where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Phrases where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Phrases where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Phrases where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Phrases whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Phrases whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
