/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Authorities;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthoritiesRecord extends UpdatableRecordImpl<AuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.authorities.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.authorities.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.authorities.name</code>. 権限名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.authorities.name</code>. 権限名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.authorities.title</code>. 漢字名称
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.authorities.title</code>. 漢字名称
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.authorities.category_id</code>. 分類ID
     */
    public void setCategoryId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.authorities.category_id</code>. 分類ID
     */
    public Long getCategoryId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthoritiesRecord
     */
    public AuthoritiesRecord() {
        super(Authorities.AUTHORITIES);
    }

    /**
     * Create a detached, initialised AuthoritiesRecord
     */
    public AuthoritiesRecord(Long id, String name, String title, Long categoryId) {
        super(Authorities.AUTHORITIES);

        setId(id);
        setName(name);
        setTitle(title);
        setCategoryId(categoryId);
        resetChangedOnNotNull();
    }
}
