/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Books;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BooksRecord extends UpdatableRecordImpl<BooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.books.id</code>. 書別ID
     */
    public void setId(Short value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.books.id</code>. 書別ID
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.books.name</code>. 書別名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.books.name</code>. 書別名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.books.name_jp</code>. 書別日本語名
     */
    public void setNameJp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.books.name_jp</code>. 書別日本語名
     */
    public String getNameJp() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BooksRecord
     */
    public BooksRecord() {
        super(Books.BOOKS);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(Short id, String name, String nameJp) {
        super(Books.BOOKS);

        setId(id);
        setName(name);
        setNameJp(nameJp);
        resetChangedOnNotNull();
    }
}
