/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Hymns;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HymnsRecord extends UpdatableRecordImpl<HymnsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.hymns.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hymns.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.hymns.name_jp</code>. 日本語名称
     */
    public void setNameJp(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hymns.name_jp</code>. 日本語名称
     */
    public String getNameJp() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.hymns.name_kr</code>. 韓国語名称
     */
    public void setNameKr(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.hymns.name_kr</code>. 韓国語名称
     */
    public String getNameKr() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.hymns.link</code>. リンク
     */
    public void setLink(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.hymns.link</code>. リンク
     */
    public String getLink() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.hymns.updated_time</code>. 更新時間
     */
    public void setUpdatedTime(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.hymns.updated_time</code>. 更新時間
     */
    public OffsetDateTime getUpdatedTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.hymns.updated_user</code>. 更新者ID
     */
    public void setUpdatedUser(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.hymns.updated_user</code>. 更新者ID
     */
    public Long getUpdatedUser() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.hymns.lyric</code>. 歌詞
     */
    public void setLyric(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.hymns.lyric</code>. 歌詞
     */
    public String getLyric() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.hymns.visible_flg</code>. 論理削除フラグ
     */
    public void setVisibleFlg(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.hymns.visible_flg</code>. 論理削除フラグ
     */
    public Boolean getVisibleFlg() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.hymns.classical</code>.
     */
    public void setClassical(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.hymns.classical</code>.
     */
    public Boolean getClassical() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HymnsRecord
     */
    public HymnsRecord() {
        super(Hymns.HYMNS);
    }

    /**
     * Create a detached, initialised HymnsRecord
     */
    public HymnsRecord(Long id, String nameJp, String nameKr, String link, OffsetDateTime updatedTime, Long updatedUser, String lyric, Boolean visibleFlg, Boolean classical) {
        super(Hymns.HYMNS);

        setId(id);
        setNameJp(nameJp);
        setNameKr(nameKr);
        setLink(link);
        setUpdatedTime(updatedTime);
        setUpdatedUser(updatedUser);
        setLyric(lyric);
        setVisibleFlg(visibleFlg);
        setClassical(classical);
        resetChangedOnNotNull();
    }
}
