/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.HymnsWork;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HymnsWorkRecord extends UpdatableRecordImpl<HymnsWorkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.hymns_work.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hymns_work.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.hymns_work.work_id</code>. ワークID
     */
    public void setWorkId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hymns_work.work_id</code>. ワークID
     */
    public Long getWorkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.hymns_work.score</code>. 楽譜
     */
    public void setScore(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.hymns_work.score</code>. 楽譜
     */
    public byte[] getScore() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.hymns_work.furigana</code>. 振り仮名
     */
    public void setFurigana(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.hymns_work.furigana</code>. 振り仮名
     */
    public String getFurigana() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.hymns_work.updated_time</code>. 更新時間
     */
    public void setUpdatedTime(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.hymns_work.updated_time</code>. 更新時間
     */
    public OffsetDateTime getUpdatedTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.hymns_work.biko</code>. 備考
     */
    public void setBiko(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.hymns_work.biko</code>. 備考
     */
    public String getBiko() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HymnsWorkRecord
     */
    public HymnsWorkRecord() {
        super(HymnsWork.HYMNS_WORK);
    }

    /**
     * Create a detached, initialised HymnsWorkRecord
     */
    public HymnsWorkRecord(Long id, Long workId, byte[] score, String furigana, OffsetDateTime updatedTime, String biko) {
        super(HymnsWork.HYMNS_WORK);

        setId(id);
        setWorkId(workId);
        setScore(score);
        setFurigana(furigana);
        setUpdatedTime(updatedTime);
        setBiko(biko);
        resetChangedOnNotNull();
    }
}
