/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Phrases;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhrasesRecord extends UpdatableRecordImpl<PhrasesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.phrases.id</code>. 節ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.phrases.id</code>. 節ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.phrases.name</code>. 節名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.phrases.name</code>. 節名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.phrases.text_en</code>. 内容
     */
    public void setTextEn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.phrases.text_en</code>. 内容
     */
    public String getTextEn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.phrases.text_jp</code>. 日本語内容
     */
    public void setTextJp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.phrases.text_jp</code>. 日本語内容
     */
    public String getTextJp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.phrases.chapter_id</code>. 章節ID
     */
    public void setChapterId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.phrases.chapter_id</code>. 章節ID
     */
    public Integer getChapterId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.phrases.change_line</code>. 改行フラグ
     */
    public void setChangeLine(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.phrases.change_line</code>. 改行フラグ
     */
    public Boolean getChangeLine() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhrasesRecord
     */
    public PhrasesRecord() {
        super(Phrases.PHRASES);
    }

    /**
     * Create a detached, initialised PhrasesRecord
     */
    public PhrasesRecord(Long id, String name, String textEn, String textJp, Integer chapterId, Boolean changeLine) {
        super(Phrases.PHRASES);

        setId(id);
        setName(name);
        setTextEn(textEn);
        setTextJp(textJp);
        setChapterId(chapterId);
        setChangeLine(changeLine);
        resetChangedOnNotNull();
    }
}
