/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Receipts;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * レシート
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReceiptsRecord extends UpdatableRecordImpl<ReceiptsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.receipts.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.receipts.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.receipts.tennpyoh_banngoh</code>.
     */
    public void setTennpyohBanngoh(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.receipts.tennpyoh_banngoh</code>.
     */
    public Long getTennpyohBanngoh() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.receipts.mise</code>.
     */
    public void setMise(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.receipts.mise</code>.
     */
    public String getMise() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.receipts.kinngaku</code>.
     */
    public void setKinngaku(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.receipts.kinngaku</code>.
     */
    public Float getKinngaku() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>public.receipts.jikann</code>.
     */
    public void setJikann(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.receipts.jikann</code>.
     */
    public LocalDateTime getJikann() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.receipts.district</code>.
     */
    public void setDistrict(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.receipts.district</code>.
     */
    public String getDistrict() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.receipts.biko</code>.
     */
    public void setBiko(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.receipts.biko</code>.
     */
    public String getBiko() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.receipts.category</code>.
     */
    public void setCategory(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.receipts.category</code>.
     */
    public String getCategory() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReceiptsRecord
     */
    public ReceiptsRecord() {
        super(Receipts.RECEIPTS);
    }

    /**
     * Create a detached, initialised ReceiptsRecord
     */
    public ReceiptsRecord(String id, Long tennpyohBanngoh, String mise, Float kinngaku, LocalDateTime jikann, String district, String biko, String category) {
        super(Receipts.RECEIPTS);

        setId(id);
        setTennpyohBanngoh(tennpyohBanngoh);
        setMise(mise);
        setKinngaku(kinngaku);
        setJikann(jikann);
        setDistrict(district);
        setBiko(biko);
        setCategory(category);
        resetChangedOnNotNull();
    }
}
