/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Roles;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.roles.id</code>. ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.roles.id</code>. ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.roles.name</code>. 名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.roles.name</code>. 名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.roles.visible_flg</code>. 論理削除フラグ
     */
    public void setVisibleFlg(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.roles.visible_flg</code>. 論理削除フラグ
     */
    public Boolean getVisibleFlg() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolesRecord
     */
    public RolesRecord() {
        super(Roles.ROLES);
    }

    /**
     * Create a detached, initialised RolesRecord
     */
    public RolesRecord(Long id, String name, Boolean visibleFlg) {
        super(Roles.ROLES);

        setId(id);
        setName(name);
        setVisibleFlg(visibleFlg);
        resetChangedOnNotNull();
    }
}
